services:
  postgres:
    container_name: postgres
    image: postgres:17.2-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wallet
    ports:
    - 5432:5432
    volumes:
    - ./data:/var/lib/postgresql/data
    - ./init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
